### PR TITLE
get-address test coverage

### PR DESCRIPTION
**Pull request by zh**
[Issue #22](https://github.com/christroutner/slp-cli-wallet/issues/22)

### CODE REVIEW

**Comment by zh** [comment]
Have problem with testing this section - https://github.com/Permissionless-Software-Foundation/slp-cli-wallet/blob/master/src/commands/get-address.js#L82 (bitcoin.com backend). Maybe the real command is working but the mock is returning `Promise` for `this.bchjs.Mnemonic.toSeed()` not `Buffer`...

**Comment by zh** [comment]
This section of code - https://github.com/Permissionless-Software-Foundation/slp-cli-wallet/blob/master/src/commands/create-wallet.js#L51 cannot be reached at all, because in the flags ( https://github.com/Permissionless-Software-Foundation/slp-cli-wallet/blob/master/src/commands/get-address.js#L149 )  `-t = testnet` is assigned to other puprose (SLP address).

Suggestion: `-s` to be used for SLP address generation, so -t can be used as testnet (this is the case in all other commands)

**Comment by zh** [comment]
commit# b24b666:

*  `bitcoin.com` code removed
* `-s` is used for SLP addresses, `-t` is back top testnet usage

**Comment by christroutner** [comment]
100 PSF tokens awarded. TXID: 850c083991da03af54396adddc58af2ced69ef6414f87248e546d7ca83735afd

**Pull request merged**
